package io.github.ideaenvswitcher.service;

import io.github.ideaenvswitcher.model.EnvProfile;
import org.jetbrains.annotations.NotNull;

import java.util.Map;

/** 将 profile 序列化为 dotenv 文本。 */
public final class DotEnvWriter {

    private DotEnvWriter() {
    }

    public static @NotNull String toDotEnvContent(@NotNull EnvProfile profile) {
        StringBuilder content = new StringBuilder();
        content.append("# Generated by Env Switcher — do not edit by hand while using the plugin\n");
        content.append("# profile=").append(profile.getName()).append('\n');
        for (Map.Entry<String, String> entry : profile.getEnv().entrySet()) {
            content.append(entry.getKey()).append('=').append(escapeValue(entry.getValue())).append('\n');
        }
        return content.toString();
    }

    static @NotNull String escapeValue(@NotNull String value) {
        if (value.isEmpty()) {
            return "\"\"";
        }
        boolean needsQuotes = value.chars().anyMatch(ch ->
                Character.isWhitespace(ch) || ch == '#' || ch == '"' || ch == '\'');
        if (!needsQuotes) {
            return value;
        }
        return '"' + value.replace("\\", "\\\\").replace("\"", "\\\"") + '"';
    }
}
